version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_product
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: productdb
    volumes:
      - mongo-data:/data/db

  springboot-app:
    build: .
    container_name: mongorestapi
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/productdb

volumes:
  mongo-data:
